services:
  
  catalog.api:
    image: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword
      - ConnectionStrings__Database=Host=catalogdb;Port=5432;Database=CatalogDb;Username=postgres;Password=Dachi123;Include Error Detail=true
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ~/.aspnet/https:/https/
    depends_on:
      - catalogdb

  catalogdb:
    container_name: catalogdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: CatalogDb
      POSTGRES_PASSWORD: Dachi123
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_data:/var/lib/postgresql/data

volumes:
  catalogdb_data: