services:
  
  event.api:
    image: event.api
    build:
      context: .
      dockerfile: Services/Event/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword
      - ConnectionStrings__Database=Host=eventdb;Port=5432;Database=EventDb;Username=postgres;Password=Dachi123;Include Error Detail=true
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ~/.aspnet/https:/https/
    depends_on:
      - eventdb

  eventdb:
    container_name: eventdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: EventDb
      POSTGRES_PASSWORD: Dachi123
    ports:
      - "5432:5432"
    volumes:
      - eventdb_data:/var/lib/postgresql/data

volumes:
  eventdb_data: