services:

  catalogdb:
    container_name: catalogdb
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: CatalogDb
      POSTGRES_PASSWORD: Dachi123
    ports:
      - "5432:5432"
    volumes:
      - catalogdb_data:/var/lib/postgresql/data

volumes:
  catalogdb_data: